### ISSUE TITLE
Create xhtml jsf views

### ISSUE THREAD

**Issue by lhannigbrinck** [SStalker/Bibo#5]

**Comment by lhannigbrinck** [comment]
@SStalker @jutta-bitter wollen wir eine/die registrierung mit flowscope machen?

**Comment by jutta-bitter** [comment]
@lhannigbrinck was ist der Unterschied zwischen flowscoped und conversationscoped? Bei flowscoped müssen auch Start und Ende definiert werden. Ansonsten finde ich die Idee sinnvoll da wir nach der Registrierung sicher noch die Daten zeigen wollen. Tatsächlich wäre das der einzige Grund für mehr als RequestScoped, oder sehe ich das falsch?

**Comment by lhannigbrinck** [comment]
Naja wollen wir das? unser augenmerk liegt auf der bibliotheks funktion. Denke dann können wir auch mir request scope arbeiten, setze mich da mal dran.

**Comment by jutta-bitter** [comment]
@lhannigbrinck also würde jetzt nach der Dateneingabe nur ein Success oder Denied kommen und dann direkt zum Login? Reicht definitiv auch und dann würde RequestScoped reichen.

**Comment by lhannigbrinck** [comment]
So war das gedacht! :+1:
