### ISSUE TITLE
first update on database fails

### ISSUE THREAD

**Issue by lhannigbrinck** [SStalker/Bibo#9]
[hier](https://github.com/SStalker/Bibo/blob/master/src/main/java/de/hsos/kbse/bibo/boundary/BookingModel.java#L66)

**Comment by lhannigbrinck** [comment]
Geht nur bei datensatz Buch: "Java EE 7 Development with Wildfly" nicht

**Comment by SStalker** [comment]
I think it is because the length oft the title from the book. It exceeds 32 characters. If we increase the amount of  chars , then it will work maybe.
